### ISSUE TITLE
how to use this docker? 

### ISSUE THREAD

**Issue by pyshltcyh** [erandal/docker-graphexp#1]
Hi, I download this dockerfile by docker pull which is 
https://hub.docker.com/r/aleopold/docker-graphexp 

and i run it, but nothing happened. I tried the following commends:

docker run docker.io/aleopold/docker-graphexp 
or 
docker run -p 8183:8183 docker.io/aleopold/docker-graphexp 
still nothing happened.

By the way, I already start my gremlin-server, so i think that gremlin-server is not a problem. 

Could you give me some instructions about how to use this docker? 

Thanks

**Comment by erandal** [comment]
Hi pyshltcyh,
This image is part of the [https://github.com/erandal/janusgraph-env](url) , if you want info you can check the readme of the repo.

In detail in the docker-compose.yml of the janusgraph env you can see : 
`  graphexp:
    image: aleopold/docker-graphexp:latest
    container_name: graphexp
    depends_on:
      - janusgraph
    ports:
      - "8183:80"
    volumes:
      - "./graphexp:/usr/share/nginx/html"
    networks:
      - janusGraphEnvNetwork`

which correspond to : 
`docker run -p 8183:80  docker.io/aleopold/docker-graphexp` for your case.
Tell me if it works for you.

**Comment by pyshltcyh** [comment]
Hi, erandal,
your reply saved me. It worked. 
Now I can visualize graphs in my browser. 
Thank you for your help.
Best Regards

**Comment by erandal** [comment]
glad to help ;)
